# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/frutl/Desktop/прога/Architecture/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/frutl/Desktop/прога/Architecture/src

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/frutl/Desktop/прога/Architecture/src/CMakeFiles /mnt/c/Users/frutl/Desktop/прога/Architecture/src/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/frutl/Desktop/прога/Architecture/src/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Program

# Build rule for target.
Program: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Program
.PHONY : Program

# fast build rule for target.
Program/fast:
	$(MAKE) -f CMakeFiles/Program.dir/build.make CMakeFiles/Program.dir/build
.PHONY : Program/fast

#=============================================================================
# Target rules for targets named simpleComputer

# Build rule for target.
simpleComputer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simpleComputer
.PHONY : simpleComputer

# fast build rule for target.
simpleComputer/fast:
	$(MAKE) -f CMakeFiles/simpleComputer.dir/build.make CMakeFiles/simpleComputer.dir/build
.PHONY : simpleComputer/fast

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/Program.dir/build.make CMakeFiles/Program.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/Program.dir/build.make CMakeFiles/Program.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/Program.dir/build.make CMakeFiles/Program.dir/main.c.s
.PHONY : main.c.s

memory.o: memory.c.o

.PHONY : memory.o

# target to build an object file
memory.c.o:
	$(MAKE) -f CMakeFiles/simpleComputer.dir/build.make CMakeFiles/simpleComputer.dir/memory.c.o
.PHONY : memory.c.o

memory.i: memory.c.i

.PHONY : memory.i

# target to preprocess a source file
memory.c.i:
	$(MAKE) -f CMakeFiles/simpleComputer.dir/build.make CMakeFiles/simpleComputer.dir/memory.c.i
.PHONY : memory.c.i

memory.s: memory.c.s

.PHONY : memory.s

# target to generate assembly for a file
memory.c.s:
	$(MAKE) -f CMakeFiles/simpleComputer.dir/build.make CMakeFiles/simpleComputer.dir/memory.c.s
.PHONY : memory.c.s

register.o: register.c.o

.PHONY : register.o

# target to build an object file
register.c.o:
	$(MAKE) -f CMakeFiles/simpleComputer.dir/build.make CMakeFiles/simpleComputer.dir/register.c.o
.PHONY : register.c.o

register.i: register.c.i

.PHONY : register.i

# target to preprocess a source file
register.c.i:
	$(MAKE) -f CMakeFiles/simpleComputer.dir/build.make CMakeFiles/simpleComputer.dir/register.c.i
.PHONY : register.c.i

register.s: register.c.s

.PHONY : register.s

# target to generate assembly for a file
register.c.s:
	$(MAKE) -f CMakeFiles/simpleComputer.dir/build.make CMakeFiles/simpleComputer.dir/register.c.s
.PHONY : register.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Program"
	@echo "... simpleComputer"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... memory.o"
	@echo "... memory.i"
	@echo "... memory.s"
	@echo "... register.o"
	@echo "... register.i"
	@echo "... register.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

